### ISSUE TITLE
Extension is not avoiding duplicate rows

### ISSUE THREAD

**Issue by WellingtonBraga** [vladsmirnov/url-rewrites#5]
Hi, 

I have installed the extension on my project in order to stop the inifinite growth of core_url_rewrite table. 
During my tests, I ran the indexer.php script to validate if the extension would avoid duplicated rows, but this is not occuring. Even with the extension installed, the execution of indexer will duplicate rows on table metioned before.

If the indexer is duplicating rows, the regular usage of the shop could result in the same situation.

Please, could you check it in order to guarantee that the extension can avoid duplication on that table?

Thanks in advance,
Wellington Braga

**Comment by vladsmirnov** [comment]
Hi Wellington Braga. 
Thank you very much for the feedback and the ticket.
Telling the truth, the module has been tested on two real shops, and on Magento's sample data database. Also, all the unit tests pass. 
Let's try to figure out, why it doesn't work in your case. Could you please give me more information regarding this issue?
1. Which version of Magento do you use?
2. Does your 'core_resource' table have an 'urlrewritemod_setup / 0.1.0 / 0.1.0' row ?
3. Did you try to flush the cache after module was installed?
4. How many times have you tried to run reindexes? (duplicates were created after each run?)
 
Thanks!

**Comment by vladsmirnov** [comment]
Can't reproduce the issue. Please feel free to comment if there any additional details.

**Comment by aboritskiy** [comment]
Hi Vlad, Hi Wellington,

I think that happens when we have multi-store setup and product has the same `url_path` value in 2 stores. I don't have a good confirmation for that yet, but from looking in to the problematic system's database that is the first thing that correlates to the problem.

At the same time, I can tell that extension significantly drops the number of additional rows generated in the `core_url_rewrite` table, from 2596 rows per indexer run to 152 rows per indexer run.
And looks like those 152 rows have something to do with the case I described above.

Best regards,
Anton Boritskiy

**Comment by aboritskiy** [comment]
used queries
1. to identify problematic products
```
SELECT target_path, COUNT(url_rewrite_id) as CNT, GROUP_CONCAT(request_path SEPARATOR ', ')
FROM core_url_rewrite
GROUP BY target_path
LIMIT 10000
```
I ran the query above before and after the indexer and then diffed the output, that pointed me to a couple of products ids, and then

2. to get insights about those products
```
SELECT * 
FROM catalog_product_entity AS e
LEFT JOIN catalog_product_entity_varchar AS ev
 ON e.entity_id = ev.entity_id AND ev.attribute_id IN (97,98)

WHERE e.entity_id = <problematic product from prev query>;
```
97 and 98 are ids of `url_key` and `url_path` attributes.
